[package]
name = "chip8"
version = "0.1.0"
edition = "2021"
authors = ["Maximilien DI DIO mdidio@pm.me"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
